name: Tests
on:
  push:
    branches:
      - develop
  pull_request: ~

jobs:
  run-tests:
    runs-on: ubuntu-latest
    services:
      dizquetv-docker:
        image: vexorian/dizquetv
        ports:
           - 8001:8000

    steps:
    - name: Sleep for 30 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '30s'

    - name: Test Docker is running
      run: "curl http://localhost:8001/api/version"

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_D_URL: http://localhost:8001
        file_name: .env

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Python dependencies
      run: make install

    - name: Test with pytest
      run: make test
